# Generated by Django 2.2.3 on 2019-08-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0003_devolução'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolução',
            name='Titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Pedido'),
        ),
    ]
