# Generated by Django 2.2.3 on 2019-09-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0007_auto_20190813_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolução',
            name='Titulo',
        ),
        migrations.AddField(
            model_name='devolução',
            name='Codigo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Pedido'),
        ),
    ]
