# Generated by Django 2.2.3 on 2019-09-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0008_auto_20190930_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolução',
            name='cod_cliente',
        ),
    ]
