# Generated by Django 2.2.3 on 2019-10-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0009_remove_devolução_cod_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolução',
            old_name='Codigo',
            new_name='Pedido',
        ),
    ]
