# Generated by Django 2.2.3 on 2019-10-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0010_auto_20191006_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolução',
            old_name='Pedido',
            new_name='Codigo',
        ),
    ]
