# Generated by Django 2.2.7 on 2019-11-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_outmed', '0011_auto_20191006_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fixo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fixo',
        ),
        migrations.CreateModel(
            name='Fone_Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(default=None, max_length=20, verbose_name='Celular')),
                ('fixo', models.CharField(default=None, max_length=20, verbose_name='Fixo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Fone_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(default=None, max_length=20, verbose_name='Celular')),
                ('fixo', models.CharField(default=None, max_length=20, verbose_name='Fixo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='End_Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(default=None, max_length=60, verbose_name='Cidade')),
                ('bairro', models.CharField(default=None, max_length=60, verbose_name='Bairro')),
                ('rua', models.CharField(default=None, max_length=50, verbose_name='Rua')),
                ('numero', models.CharField(default=None, max_length=10, verbose_name='Numero')),
                ('cep', models.CharField(default=None, max_length=10, verbose_name='CEP')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='End_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(default=None, max_length=60, verbose_name='Cidade')),
                ('bairro', models.CharField(default=None, max_length=60, verbose_name='Bairro')),
                ('rua', models.CharField(default=None, max_length=50, verbose_name='Rua')),
                ('numero', models.CharField(default=None, max_length=10, verbose_name='Numero')),
                ('cep', models.CharField(default=None, max_length=10, verbose_name='CEP')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_outmed.Cliente')),
            ],
        ),
    ]
